kind: BuildConfig
apiVersion: v1
metadata:
  name: hello-word-wf-master-pipeline
  labels:
    app: hello-word-wf
spec:
  resources:
    requests:
      cpu: 2000Mi
      memory: 1G
  source:
    git:
      ref: master
      uri: "https://github.com/alacambra/hello.git"
    type: Git
  strategy:
    type: JenkinsPipeline
    jenkinsPipelineStrategy:
      jenkinsfilePath: Jenkinsfile
      env:
        - name: SERVICE_URI
          value: http://hello-world-wf.devops.svc:8080